### PR TITLE
Use mouseenter and leave; Do not dispatch focus event needlessly.   BLOCKED BY PR #125

### PR DESCRIPTION
**Pull request by aneyzberg**

### CODE REVIEW

**Comment by aneyzberg** [comment]
completes #124

**Comment by camwest** [comment]
I've manually verified this fixes the "Choosing an option with the mouse" scenario in both Firefox and Edge

**Comment by camwest** [comment]
Also I expect a new failing test for this fix.

**Comment by aneyzberg** [comment]
@camwest I can write a test that tests that `select-option` is listening to `mouseenter` and `mouseleave` rather than `mouseover` or `mouseout`, and that once `focus` is set, we do not set it again. However to really test this, i would need to run WCT in firefox and edge.

**Comment by aneyzberg** [comment]
This branch currently has WCT specs failing that are fixed in https://github.com/orion-ui/orion/pull/125/files

So once that PR is merged. This branched needs to be rebased to fix the spec failure

**Comment by aneyzberg** [comment]
Github ended up closing this PR when I rebased this branch with master because https://github.com/orion-ui/orion/pull/125 had the same solution. So the code for this is already in master.

**Pull request closed without merging**
