### PR TITLE
Bugs/fix ng repeat select

### PR DESCRIPTION
**Pull request by aneyzberg**

### CODE REVIEW

**Comment by aneyzberg** [comment]
Completes #98

**Comment by aneyzberg** [comment]
@camwest - Couple of questions. 

1)Initially looking at your feedback, it seemed like the  simplest and most general solution would be to move the  `clearChildren(this);` function we have been using, into the element.js constuctor, so that we preclude all elements from having children.  However this seems to be a little too strict, since it prevents buttons from having text nodes as children.  

I wonder if allowing for components to remove children in their respective constructors when needed is appropriate or if you would like to see a more strict solution in place. 

2)  As far as our ensure methods and querying the DOM - is there any concern about performance with regards to that?

**Comment by camwest** [comment]
1. I'd like to avoid the situation where we build a component and don't test it with ngRepeat and then accidentally release a bug. Having each component require clearChildren in it's constructor doesn't solve that problem. Can you come up with a better solution?

2. I don't think we're optimized for performance at all right now so the answer is no, let's focus on correctness and later we can optimize for performance.

**Comment by aneyzberg** [comment]
@camwest ok, that is helpful. Thank you!

**Comment by camwest** [comment]
Fixed in #119

**Pull request closed without merging**
