### PR TITLE
React button

### PR DESCRIPTION
**Pull request by nfiniteset**
Wrap web component in a react component.

### CODE REVIEW

**Comment by nfiniteset** [comment]
Heads up. The code as of commit `f1d46d3` isn't working as intended. I imported the Orion web component to a const `button`, which shares a name with a react component. No errors were thrown, but React rendered the React button rather than ours. 

We have to watch out for this for components that share names with real components. We should always call our components `OrionButton` (or something) to prevent this.

**Comment by nfiniteset** [comment]
This is ready for review @camwest

**Comment by camwest** [comment]
@nfiniteset I don't understand what you mean by "I imported the Orion web component to a const button, which shares a name with a react component" is this still relevant?

**Comment by nfiniteset** [comment]
What I meant there was that if you import and web component with the same name as a built-in react component, the react components gets used instead of the web component you import. It's just a warning for us and for our users.

**Comment by camwest** [comment]
@nfiniteset ok, I don't understand what you mean still. Can you show me a code sample?

**Comment by nfiniteset** [comment]
**BAD EXAMPLE**
In the the code sample below I expected `button` to be our web component button. Instead the browser shows a native browser button.
```javascript
import React from 'react';
import button from '@orion-ui/components/lib/2016-12-01';

function Button(props) {
  return (
    <button onClick={props.onClick} color={props.color} background={props.background}>
      {props.children}
    </button>);
}
```

**GOOD EXAMPLE**
In this example, our web component button appears as expected.
```javascript
import React from 'react';
import '@orion-ui/components/lib/2016-12-01';

function Button(props) {
  return (
    <orion-button onClick={props.onClick} color={props.color} background={props.background}>
      {props.children}
    </orion-button>);
}
```

**Comment by camwest** [comment]
OK - now I understand thank you. I think you're misinterpreting how html web components work. 

* In the bad example `@orion-ui/components/lib/2016-12-01/button` does not actually export a react component. It exports a HTMLElement constructor.
* In React there is a distinction between uppercase and lowercase tag names. React treats lowercase tag names as HTML elements and uppercase tag names as Composite elements (Roughly, a React component instances)

See https://facebook.github.io/react/docs/jsx-in-depth.html#html-tags-vs.-react-components for more information.

**Comment by camwest** [comment]
@nfiniteset I made a commit to this PR. Please review. 

* I'd rather we avoid ES2015 modules for now for our own code as they really mess up debugging. 
* When I removed the references to the components and style library inside react-playground it stopped working so I fixed the issues related to that.

**Pull request merged**
