### PR TITLE
Bugs/Select rendered twice in ngRepeat

### PR DESCRIPTION
**Pull request by aneyzberg**
Remove menu when select element is disconnected.

Completes #98

### CODE REVIEW

**Comment by camwest** [comment]
Also this addresses the chrome issue in #98 but not the other two issues so I'm not going to make it as done yet.

**Comment by aneyzberg** [comment]
@camwest I am going to close this PR. Sean and I made a bunch of small PR's yesterday. The code that actually fixes the ng-repeat has already been merged in a separate PR. This issue is difficult to unit test because the issue is actually needing to wait for the select element to be defined on Window before the angular wrapper executes. To test this, we would need to set up testing for the angular wrapper.

**Comment by camwest** [comment]
OK understood.

**Comment by camwest** [comment]
I just tried on master and it seems the repeated select but is still there. Are you 100% positive we don't need the changes in this PR?

**Comment by aneyzberg** [comment]
I am double checking right now. Just to make sure.

**Comment by aneyzberg** [comment]
closed in favor of #114

**Pull request closed without merging**
